services:
  mongo:
    image: mongo:latest
    container_name: iot_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    command: mongod --auth
    volumes:
      - mongo_data:/data/db

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: iot_mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt.conf:/mosquitto/config/mosquitto.conf
    command: mosquitto -c /mosquitto/config/mosquitto.conf

volumes:
  mongo_data: